name: Test Runner
on: [push]
jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        os:
         - ubuntu-20.04
        python-version:
          - 2.7
          - 3.6
          - 3.8

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install -U -r tests/requirements.txt

      - name: Run tests with coverage
        run: coverage run --source . -m unittest tests

      - name: Print coverage report
        run: coverage report -m

