name: Test Runner
on: [push]
jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        include:

          - test-name: ubuntu-20.04-python-2.7
            os: ubuntu-20.04
            python-version: 2.7

          - test-name: ubuntu-20.04-python-3.6
            os: ubuntu-20.04
            python-version: 3.6

          - test-name: ubuntu-20.04-python-3.8
            os: ubuntu-20.04
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install -U -r tests/requirements.txt

      - name: Run tests with coverage
        run: coverage run --source . -m unittest tests

      - name: Print coverage report
        run: coverage report -m

      - name: Upload coverage to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
        run: |
          python -m pip install --upgrade coveralls
          coveralls --service=github

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          python -m pip install --upgrade coveralls
          coveralls --service=github --finish

