name: Tests
on: [push]
jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        include:

          - test-name: ubuntu-20.04-python-2.7
            os: ubuntu-20.04
            python-version: 2.7

          - test-name: ubuntu-18.04-python-3.4
            os: ubuntu-18.04
            python-version: 3.4

          - test-name: ubuntu-20.04-python-3.5
            os: ubuntu-20.04
            python-version: 3.5

          - test-name: ubuntu-20.04-python-3.6
            os: ubuntu-20.04
            python-version: 3.6

          - test-name: ubuntu-20.04-python-3.7
            os: ubuntu-20.04
            python-version: 3.7

          - test-name: ubuntu-20.04-python-3.8
            os: ubuntu-20.04
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Setup pebble
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u github.com/letsencrypt/pebble/...
            cd $GOPATH/src/github.com/letsencrypt/pebble && go install ./...
            pebble -h || true

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          pip install -U -r tests/requirements.txt

      - name: Run tests with coverage
        run: |
          export PEBBLE_BIN=$(go env GOPATH)/bin/pebble
          $PEBBLE_BIN -h || true
          coverage run --source . --omit ./setup.py -m unittest tests

      - name: Run tests against staging
        env:
          STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        run: |
          sudo apt install sshfs
          touch $HOME/sshfs_key.pem
          chmod 600 $HOME/sshfs_key.pem
          echo "$STAGING_SSH_KEY" > $HOME/sshfs_key.pem
          echo "----------1"
          echo "$STAGING_SSH_KEY"
          echo "----------2"
          cat $HOME/sshfs_key.pem
          echo "----------3"
          pwd
          echo "$HOME"
          echo "----------4"
          mkdir -p /tmp/challenge-files
          sshfs -o debug -oIdentityFile=$HOME/sshfs_key.pem -p 2299 challengeuser@staging.gethttpsforfree.com:/acme-challenge /tmp/challenge-files
          ls -lah /tmp/challenge-files
          fusermount -u /tmp/challenge-files

      - name: Print coverage report
        run: coverage report -m

      - name: Upload coverage to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_SERVICE_NAME: github-actions
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
        run: |
          python -m pip install --upgrade coveralls
          coveralls

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade coveralls
          coveralls --service=github --finish

